### ISSUE TITLE
Client Crash on join

### ISSUE THREAD

**Issue by jackthehack21** [TwistedAsylumMC/PocketNode#2]
### Issue description
This is issue is a continuation of the last issue, on old repo.

When starting a server, and attempting to join the client will freeze at last stage then crash MC

- Expected result: Joining the world.
- Actual result: Client Crash

### Steps to reproduce the issue
1. Start Server
2. Join Server

### OS and versions
* PocketNode: 0.0.5 (All commits by TwistedAsylumMC)
* Node: 8.x, 9.x & 10.x
* Server OS: Windows
* Game version: PE and Win10

### Error log
N/A - Shows clients cause of disconnect as timeout.

### Extra Notes:
Please only comment on this issue if you find a suspect or culprit in code currently i believe its either Chunk formatting or a packet not being sent/handled correctly
But nothing has concrete evidence.

**Comment by ErkamKahriman** [comment]
I can't join 
and console will be spammded
![image](https://user-images.githubusercontent.com/16340573/51075484-622f2480-168c-11e9-9089-c20c33153389.png)

**Comment by TwistedAsylumMC** [comment]
We are aware, we are unknown of what is causing these problems

**Comment by ErkamKahriman** [comment]
Shit i want to take a look for performance do you think that you can fix the join bug / problem ?

**Comment by jackthehack21** [comment]
Want to look for performance?
What would you be looking for lol
You can’t place break do anything but move

**Comment by ErkamKahriman** [comment]
But i want to test it with 1.8 1.8 has more features and packets so ...

**Comment by jackthehack21** [comment]
*face palms*
Listen from what it sounds like your not at the right place, this software only works on 1.5- and the ONLY feature is you can move and run commands.
There are no items or blocks or whatever.
Doesn’t matter MCPE updates have it, the server has not got any of it implemented.
So I think your in the wrong place if your even considering using this.
I suggest PocketMine-MP or Altay they both have way more features.

Good day.

**Comment by xXNiceYT** [comment]
It’s caus3d by terrain and player skin and other niggumers idk I am not js dev chunks crap

**Comment by jackthehack21** [comment]
Already looked into, nothing found.

**Comment by jackthehack21** [comment]
Closed, As i'm working on 1.5.

**Comment by nobody5050** [comment]
Please lock until fix is found

**Comment by TwistedAsylumMC** [comment]
Will open until resolved for 1.6+

**Comment by jackthehack21** [comment]
Client crash fixed, different problems have arose

**Comment by jackthehack21** [comment]
Fore more info on this issue please see the repo at its new home, https://github.com/PocketNode-Revive/Pocketnode/issues/1
